### ISSUE TITLE
Update code for anax checking exchange version

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#576] opened 2018-03-15 15:26 UTC
A couple small things for now:

- uncomment the code to call the exchange /admin/version method. If it returns http code 200, use/check the version it returns. But if it returns non-200 (like it will until wiotp opens that up), use the hardcoded version.
- as a general rule, REQUIRED_EXCHANGE_VERSION should be set to the preferred version of the exchange that will allow anax to run all new features.
- in conjunction with the previous bullet, if the exchange version isn't at least REQUIRED_EXCHANGE_VERSION, log an error msg, but don't exit anax. Because i most cases anax will still run, just not support the latest features.

For sometime in the future:

- maybe add another constant PREFERRED_EXCHANGE_VERSION that means the version needed to use all new features. Then REQUIRED_EXCHANGE_VERSION could be set to the version of the exchange that is needed or else anax will panic.

**Comment by linggao** [comment] 2018-03-30 01:38
It is duplicate of issue 577.

**Closed** 2018-08-30 12:51 UTC
Labels: duplicate
