### ISSUE TITLE
hzn register error recovery did not work

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2156] opened 2020-10-08 13:13 UTC
The original error below was caused by an exchange problem, but the recovery that `hzn register` tried to do didn't work. Two issues:

1. The timeout of 15 minutes for the regular unregister seems excessive. Under what conditions does it take 15 minutes to unregister?
1. When it finally tried to unregister with deep clean, it failed. But as soon as it was done i ran `hzn unregister -fD` and it successfully unregistered it and put it back into `unconfigured` state.

```
2020-10-08 05:36:23 Registering the edge node...
hzn register -m 'bp11' -o 'mycluster'  -n '99aaf55c-c8a5-4847-a2de-e2c48b456027:ac7997bcee810532ff52f3db1801cb4262e684061af2'    
Horizon Exchange base URL: https://cp-console.ieam-roks-stg-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-exchange/v1
Node mycluster/99aaf55c-c8a5-4847-a2de-e2c48b456027 exists in the Exchange
No pattern or node policy is specified. Will proceeed with the existing node policy.
Initializing the Horizon node with node type 'device'...
Error initializing the node: error adding architecture for the exchange node. Invocation of PATCH at https://cp-console.ieam-roks-stg-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-exchange/v1/orgs/mycluster/nodes/99aaf55c-c8a5-4847-a2de-e2c48b456027 failed invoking HTTP request, status: 500, response: {"code":"internal_error","msg":"node 'mycluster/99aaf55c-c8a5-4847-a2de-e2c48b456027' not inserted or updated: ERROR: cannot execute UPDATE in a read-only transaction"}

Critical error encountered in registration. Attempting to undo registration steps to leave node in the unregistered state.
Waiting for Horizon node unregister to complete: Timeout in 885 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 870 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 855 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 840 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 825 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 810 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 795 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 780 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 765 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 750 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 735 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 720 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 705 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 690 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 675 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 660 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 645 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 630 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 615 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 600 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 585 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 570 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 555 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 540 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 525 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 510 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 495 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 480 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 465 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 450 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 435 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 420 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 405 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 390 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 375 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 360 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 345 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 330 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 315 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 300 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 285 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 270 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 255 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 240 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 225 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 210 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 195 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 180 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 165 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 150 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 135 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 120 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 105 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 90 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 75 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 60 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 45 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 30 seconds ...
Waiting for Horizon node unregister to complete: Timeout in 15 seconds ...
Waiting for agent service to restart and checking the node configuration state...
Error unregistering node. Retrying.
Waiting for agent service to restart and checking the node configuration state...
Error unregistering node. Retrying.
Waiting for agent service to restart and checking the node configuration state...
Failed to unregister node. Attempting a deep clean of the node.
Waiting for agent service to restart and checking the node configuration state...
Error: Failed to deep clean the node. Timeout waiting for node change to 'unconfigured' state.
08-10-2020 05:52:35.787 INFO  [pool-1-thread-1] o.s.c.DeviceTransferOwnershipClient.to2 - reuse protocol is enabled
08-10-2020 05:52:35.804 INFO  [pool-1-thread-1] org.sdo.cri.CipherUtils.encodeAndEncipher - {"hmac":[1,0,"PQ=="],"n6":"Bt+cqwUylhNDNLFJRy9bQA=="}
08-10-2020 05:52:35.814 INFO  [pool-1-thread-1] o.s.c.DeviceTransferOwnershipClient.httpPost - HttpRequest: http://bruce-dev11.fyre.ibm.com:8042/mp/113/msg/50 POST
{Authorization=[Bearer 99AAF55CC8A54847A2DEE2C48B456027], Content-Type=[application/json]}
{"ct":[[16,"GuGNFjy85Yk4AWV2AAAAtA=="],53,"tGDCWDI9/kWdfA+IUwD4JUamzvr3OMx5pXfw+J3JSdttV3MUlETLdOZk2sm4gXDVkDvkGWM="],"hmac":[32,"PZG2EVOgG0EhgGR7mRj5ANrXo62kZlcZHtb/pANjZ6I="]}
08-10-2020 05:52:36.136 INFO  [pool-1-thread-1] o.s.c.DeviceTransferOwnershipClient.httpPost - HttpResponse: (POST http://bruce-dev11.fyre.ibm.com:8042/mp/113/msg/50) 200
{authorization=[Bearer 99AAF55CC8A54847A2DEE2C48B456027], content-length=[149], content-type=[application/json], date=[Thu, 08 Oct 2020 12:52:36 GMT]}
{"ct":[[16,"7hKhyXSZKtQgyhRxAAAm7A=="],33,"t+RKzZlnfPAvgRaFopuhnJU9pBdsZPlLPpotKdsjGrjE"],"hmac":[32,"LEfPQOMtx2gX0aqNjIWkWqYkskRhjIU2TmUgVMCL4PQ="]}
08-10-2020 05:52:36.141 INFO  [pool-1-thread-1] org.sdo.cri.CipherUtils.decipherAndDecode - {"n7":"p5Qgr281JQhP2/eT0/yT8w=="}
08-10-2020 05:52:36.148 INFO  [main] org.sdo.cri.device.DeviceApp.lambda$applicationRunner$1 - device onboarding ends
Waiting for agreement for ibm.helloworld ..........^C
root@bp11:~/sdo# hzn node list
{
  "id": "99aaf55c-c8a5-4847-a2de-e2c48b456027",
  "organization": "mycluster",
  "pattern": "",
  "name": "bp11",
  "nodeType": "device",
  "token_last_valid_time": "2020-10-08 05:36:24 -0700 PDT",
  "token_valid": true,
  "ha": false,
  "configstate": {
    "state": "unconfiguring",
    "last_update_time": "2020-10-08 05:36:25 -0700 PDT"
  },
  "configuration": {
    "exchange_api": "https://cp-console.ieam-roks-stg-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-exchange/v1/",
    "exchange_version": "2.51.0",
    "required_minimum_exchange_version": "2.44.0",
    "preferred_exchange_version": "2.44.0",
    "mms_api": "https://cp-console.ieam-roks-stg-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-css",
    "architecture": "amd64",
    "horizon_version": "2.27.0-123"
  }
}
root@bp11:~/sdo# hzn unregister -fD
Backing up eventlogs...
Saved eventlog into file /tmp/eventlogs_bkp_2020-10-08T05:53:42-07:00.txt
Unregistering this node, cancelling all agreements, stopping all workloads, and restarting Horizon...
bad HTTP code 400 from DELETE http://localhost:8510/node?block=true&deepClean=true: The node must be in configured or configuring state in order to unconfigure it.

Starting external deep clean ...
Deleting local horizon DB...
Deleting service containers...
Starting horizon...
Waiting for agent service to restart and checking the node configuration state...
Horizon node unregistered. You may now run 'hzn register ...' again, if desired.
root@bp11:~/sdo# hzn node list
{
  "id": "99aaf55c-c8a5-4847-a2de-e2c48b456027",
  "organization": null,
  "pattern": null,
  "name": null,
  "nodeType": null,
  "token_last_valid_time": "",
  "token_valid": null,
  "ha": null,
  "configstate": {
    "state": "unconfigured",
    "last_update_time": ""
  },
  "configuration": {
    "exchange_api": "https://cp-console.ieam-roks-stg-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-exchange/v1/",
    "exchange_version": "2.51.0",
    "required_minimum_exchange_version": "2.44.0",
    "preferred_exchange_version": "2.44.0",
    "mms_api": "https://cp-console.ieam-roks-stg-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-css",
    "architecture": "amd64",
    "horizon_version": "2.27.0-123"
  }
}
```

**Comment by linggao** [comment] 2020-10-08 13:53
When -D is specified with `hzn unregister`, we should always to the deep clean part even there are errors for the other parts.

**Comment by gripson** [comment] 2020-10-14 16:43
@joewxboy, @linggao, @joewxboy could you please assign this issue to me? If this issue hasn't been solved yet.

**Comment by gripson** [comment] 2020-10-28 00:25
@bmpotter 
1. Conditions could be anax is not up or node is not in "unconfigured" state. Here timeout is the second reason according to the Error info you got -  "Error: Failed to deep clean the node. Timeout waiting for node change to 'unconfigured' state." 

2. When 'hzn register' fails, it automatically unregisters node only by calling horizon DELETE /node api to put node back into the unconfigured state. It looks sometimes that api call could fail.

Solution:  add external deep clean to remove local db and clean up all the containers, etc.

Code is ready, but still try to reproduce the issue for solution verification.

**Comment by bmpotter** [comment] 2020-10-28 10:51
@gripson 

It looks to me like there are 2 different unregistration attempts:

1. a "regular" unregistration
1. a "deep clean" unregistration

This is appropriate and we want to keep that behavior. (We don't want to do the deep clean unless the regular fails, because with deep clean the agent loses some useful history.) Again, the 2 problems that should be fixed are:

1. on the "regular unregistration, it shouldn't wait 15 minutes before deciding that's not working. It should be more like 3 minutes, but you should consult with ling or dave about the best value, based on what unregistration is doing.
1. as you noted above, the deep clean failed and it seems clear that it isn't doing everything that an external `hzn unregister -fD` does, so that should be corrected.

**Comment by gripson** [comment] 2020-10-28 12:00
@bmpotter 
You are right.

@linggao @dabooz 
1. Shall I change the timeout of the "regular unregistration" in ` hzn register` failure to 3 min ?  PS: I also find that there is an annotation for the `DeleteHorizonNode` function says "...timeout in 3 minutes."

2. I am wondering, is it appropriate to invoke external deep clean function after the "deep clean" unregistration(by calling anax api) fails; or it is better to delegate external deep clean operation to user self, which is adding an addition error information to inform user, like "The node was not successfully unregistered, please use 'hzn unregister -D' to ensure the node is completely reset.".

**Comment by linggao** [comment] 2020-10-28 20:41
@gripson It seems that only (1) is needed that is change the timeout from 15 minutes to 3 minutes. @booz please confirm that this will not affect the scaling.
For (2), hzn unregister -fD has a 400 error "bad HTTP code 400 from DELETE http://localhost:8510/node?block=true&deepClean=true: The node must be in configured or configuring state in order to unconfigure it.", this part has been fixed by another issue https://github.com/open-horizon/anax/issues/2155. So no changes should be made.

**Comment by gripson** [comment] 2020-10-28 23:01
@linggao 

Sorry, maybe I did not give clear words for (2) in my previous comment. 

As @bmpotter said, both **hzn register error recovery** and `hzn unregistered -D ` execute node deep clean, but their final clean work results are different. From the user perspective, it is an issue because both deep clean look no different literally, so they are supposed to give the same result. However, actually, they are different because "hzn unregistered -D" execute bash command to force the removal of all node resources once Delete HTTP call fails, which **hzn register error recovery** doesn't do.

Hence, going back to my previous question, shall we keep the inconsistency result of deep clean between the `hzn unregistered -D ` and **hzn register error recovery**?

**Comment by dabooz** [comment] 2021-01-11 16:13
@gripson Are you still awaiting an answer to this question?

**Comment by gripson** [comment] 2021-01-11 22:24
@dabooz Yes. 

I need you to confirm if it is necessary to change the regular unregister timeout from 15 minutes to 3 minutes. If so, As @linggao mentioned that we need you to confirm if this change affects scaling.
> @gripson It seems that only (1) is needed that is change the timeout from 15 minutes to 3 minutes. @dabooz please confirm that this will not affect the scaling.

The second question is shall we keep the inconsistency action of deep clean between the hzn unregistered -D and hzn register error recovery?

**Comment by dabooz** [comment] 2021-03-24 14:26
@gripson Yes, it is ok to change the default timeout to 3 mins.
For your second question, the problem is that the error recovery did attempt a deep clean but it also failed. In fact, the code tries to deep clean twice, and the second deep clean is supposed to be exactly the same as using unregister -D (there is no difference). But, the second deep clean failed (we think because of issue 2155), so the logic was correct. However, the user should have been given instructions in the error message to run hzn unregister -D. That is, the error message should change to "Failed to deep clean the node. Please run hzn unregister -D to fully clean the node."

**Closed** 2023-04-11 19:46 UTC
Labels: bug, p3
