### ISSUE TITLE
Dockerfile performance improvements

### ISSUE THREAD

**Issue by bencourliss** [open-horizon/anax#1778] opened 2020-05-19 17:38 UTC
The Dockerfiles for the Agbot, anax-in-k8s, anax-in-container, and CSS/ESS can be streamlined to reduce image layers and reduce image sizes.
* There are several packages installed via microdnf: `wget iptables vim-minimal procps tar` that can be either removed if not needed, or removed after being used.
* Reduce the image sizes of Go binaries by removing debugging information. Either set linker flags`-ldflags="-s -w" ` or do a `strip` on the binary after its built.
* Investigate using Ultimate Packer for eXecutables (UPX) to reduce image size. See [this blog post](https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/).
* Reduce the number of layers by combining `RUN` commands. In particular, the mkdir's, the adduser, and the chown `RUN` commands can be combined.
* In certain Dockerfiles, both `wget` and `curl` are being used and installed. Choose one and don't install the other.

**Comment by IntelliJIN** [comment] 2020-08-27 18:04
@joewxboy, @linggao could you please assign this issue to me?

**Comment by MaxMcAdam** [comment] 2021-09-29 20:45
duplicate of 2038

**Closed by MaxMcAdam** 2021-09-29 20:45 UTC
Labels: feature, softserve
