### ISSUE TITLE
Surface "toomanyrequests" error in 'hzn eventlog list'

### ISSUE THREAD

**Issue by t-fine** [open-horizon/anax#2189] opened 2020-11-04 21:53 UTC
```You are receiving this email because of a policy change to Docker products and services you use. On Monday, November 2, 2020 at 9am Pacific Standard Time, Docker will begin enforcing rate limits on container pulls for Anonymous and Free users. Anonymous (unauthenticated) users will be limited to 100 container image pulls every six hours, and Free (authenticated) users will be limited to 200 container image pulls every six hours, when enforcement is fully implemented. Docker Pro and Team subscribers can pull container images from Docker Hub without restriction, as long as the quantities are not excessive or abusive.```

With this new docker policy there may be errors encountered when the agent tries to pull the requested image, but currently it only shows as the following in the output of `hzn eventlog list`:
``` 
"2020-11-04 13:47:05:   Error loading image for mycluster/perfhznmodel100.helloworld.",
  "2020-11-04 13:47:05:   Start terminating agreement for perfhznmodel100.helloworld. Termination reason: image fetching failed",
  "2020-11-04 13:47:05:   Complete terminating agreement for perfhznmodel100.helloworld. Termination reason: image fetching failed",
```

When Doug "enabled more debugging" in anax he was able to determine it was due to this request limit because of the following message:
```Error: API error (500): toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit```

**Comment by dlarson04** [comment] 2020-11-04 22:30
here are other agent logs 

```I1104 14:28:48.592521    9836 imagepull.go:175] Max pull attempts reached (3) for fetching Docker image openhorizon/ibm.helloworld_amd64@sha256:c1851d15aa4d3573dde93a94c57c815730853a81e3e6b4e919828e81587e7d61.Docker client error occurred API error (500): toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
E1104 14:28:48.592568    9836 imagepull.go:135] Docker image pull(s) failed for docker image openhorizon/ibm.helloworld_amd64@sha256:c1851d15aa4d3573dde93a94c57c815730853a81e3e6b4e919828e81587e7d61. Error: API error (500): toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.```

**Comment by linggao** [comment] 2021-01-13 19:00
Duplicate of #2227

**Closed** 2021-01-13 19:01 UTC
Labels: bug, duplicate, p3
