### ISSUE TITLE
Modify agent behavior to reduce surge of network traffic after a message is received

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#1824] opened 2020-05-29 19:06 UTC
In steady state, the agents back off their heartbeat to up to 2 minutes very nicely. But, when they receive a message, the heartbeat goes back to the minimum of 10sec so when a policy on the hub is deleted or created and the agents get notified, they start polling at 10sec and then back off again. This  drives an increase in exchange traffic if there are thousands of agents. 

What I think happens is that when each agent receives a message the heartbeat interval immediately drops back to the default 10s (so if it was 2 min, it is now 10sec).  At 4k agents, this is a big increase (2000 req/min to 24000 req/min) in traffice to the exchange. 

One idea that I think would reduce this exchange cpu spike is when the agents get a message, if the heartbeat is greater than the default 10sec, that the heartbeat interval goes to 1/2 of what it was… or maybe 1/4 of what it was.. If there is only the cancel message to the agents this would only cause an increase of 2000 req/min to 4000 req/min (heartbeat dropping from 2 min to 1 min). Admittedly this would increase the amount of time for agents to get agreements in the case where the cancel message is followed shortly by a new proposal message… In this case though, the first message (cancel) would cause the heartbeat interval to drop to 1 minute but then the proposal message (say on the next heartbeat after 1 min) would cause it to drop again in half to 30 sec.

Another possibility is to increase the minimum heartbeat interval to 30 seconds... This again would have less of a surge of traffic for thousands of agents going from the back off time of 2 minutes just down to 30seconds.

**Comment by linggao** [comment] 2020-06-17 21:58
Feature 1863 will handle it.

**Comment by LiilyZhang** [comment] 2020-09-16 15:46
duplicate of 1863. Closed

**Closed by LiilyZhang** 2020-09-16 15:46 UTC
Labels: feature, perf
