### ISSUE TITLE
'hzn unregister -fD' when in unconfiguring state gives error message

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/anax#2155] opened 2020-10-08 13:01 UTC
When i run `hzn unregister -fD` when the node is in `unconfiguring` state gives error message: The node must be in configured or configuring state in order to unconfigure it (altho it does seem to unregister it). But when the node is stuck in `unconfiguring` state, that is one of the cases in which you need to unregister with deep clean, so it shouldn't give any error msg.

You should also consider figuring out a way to intentionally get an edge node stuck in the unconfiguring and configuring states, so that you can have test cases for that in e2edev.

```
root@bp11:~/sdo# hzn node list
{
  "id": "99aaf55c-c8a5-4847-a2de-e2c48b456027",
  "organization": "mycluster",
  "pattern": "",
  "name": "bp11",
  "nodeType": "device",
  "token_last_valid_time": "2020-10-08 05:36:24 -0700 PDT",
  "token_valid": true,
  "ha": false,
  "configstate": {
    "state": "unconfiguring",
    "last_update_time": "2020-10-08 05:36:25 -0700 PDT"
  },
  "configuration": {
    "exchange_api": "https://cp-console.ieam-roks-stg-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-exchange/v1/",
    "exchange_version": "2.51.0",
    "required_minimum_exchange_version": "2.44.0",
    "preferred_exchange_version": "2.44.0",
    "mms_api": "https://cp-console.ieam-roks-stg-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-css",
    "architecture": "amd64",
    "horizon_version": "2.27.0-123"
  }
}
root@bp11:~/sdo# hzn unregister -fD
Backing up eventlogs...
Saved eventlog into file /tmp/eventlogs_bkp_2020-10-08T05:53:42-07:00.txt
Unregistering this node, cancelling all agreements, stopping all workloads, and restarting Horizon...
bad HTTP code 400 from DELETE http://localhost:8510/node?block=true&deepClean=true: The node must be in configured or configuring state in order to unconfigure it.

Starting external deep clean ...
Deleting local horizon DB...
Deleting service containers...
Starting horizon...
Waiting for agent service to restart and checking the node configuration state...
Horizon node unregistered. You may now run 'hzn register ...' again, if desired.
root@bp11:~/sdo# hzn node list
{
  "id": "99aaf55c-c8a5-4847-a2de-e2c48b456027",
  "organization": null,
  "pattern": null,
  "name": null,
  "nodeType": null,
  "token_last_valid_time": "",
  "token_valid": null,
  "ha": null,
  "configstate": {
    "state": "unconfigured",
    "last_update_time": ""
  },
  "configuration": {
    "exchange_api": "https://cp-console.ieam-roks-stg-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-exchange/v1/",
    "exchange_version": "2.51.0",
    "required_minimum_exchange_version": "2.44.0",
    "preferred_exchange_version": "2.44.0",
    "mms_api": "https://cp-console.ieam-roks-stg-70ea81cdef68a2eb78ece6d890b7dad3-0000.us-south.containers.appdomain.cloud/edge-css",
    "architecture": "amd64",
    "horizon_version": "2.27.0-123"
  }
}
```

**Comment by linggao** [comment] 2020-10-08 14:17
1. The message "The node must be in configured or configuring state in order to unconfigure it" should be removed if -D is pecified because the deep clean part will clean up the node and bring it to "unconfigured" state.
2. Add a test case in e2edev.

**Comment by sirotsinskuy** [comment] 2020-10-26 13:23
Working on it. @joewxboy please assign this issue to me

**Comment by linggao** [comment] 2020-10-26 13:30
Removed the requirement for adding it to e2edev testing because it is hard to reproduce. The manually test has to use a third party tool to alter the node status in the db. We should not introduce a third party for this.

**Closed** 2020-11-10 21:38 UTC
Labels: PR submitted, bug, p3, softserve
