### ISSUE TITLE
agent-install/agent-install.sh doesn't recognize K3s correctly

### ISSUE THREAD

**Issue by AlexKoe** [open-horizon/anax#2326] opened 2021-02-24 14:56 UTC
The following check fails with K3s

```
if [[ "$INTERNAL_URL_FOR_EDGE_CLUSTER_REGISTRY" == "" ]]; then
            # check if using local cluster or remote ocp
            if $KUBECTL cluster-info | grep -q -E 'Kubernetes master.*//(127|172|10|192.168)\.'; then
                # using small kube
```

and then incorrectly assumes an OCP cluster.

Reason: 
k3s kubectl cluster-info returns 'Kubernetes control plane' instead of 'Kubernetes master'

Example:

```
k3s kubectl cluster-info
Kubernetes control plane is running at https://127.0.0.1:6443
```

**Comment by LiilyZhang** [comment] 2021-04-13 13:39
This is dupe of issue #2345. Related PR is: https://github.com/open-horizon/anax/pull/2348/files

**Closed** 2021-04-15 14:16 UTC
Labels: feature, p2
