### ISSUE TITLE
Operator pod(s) stuck in "Terminating" state

### ISSUE THREAD

**Issue by t-fine** [open-horizon/anax#1788] opened 2020-05-21 18:22 UTC
For a little more information here, I had my cluster node `tfine-cluster-apollo1` registered with an operator of mine but when I ran `hzn unregister -fD` the pods remained in the terminating state 
```
root@gormand1:~# kubectl get pod -n openhorizon-agent
NAME                                          READY   STATUS        RESTARTS   AGE
agent-6d8b8895f-bpwm9                         1/1     Running       0          2d19h
example-ibmserviceoperator-7555bb584c-7t2xc   1/1     Terminating   0          6m22s
example-ibmserviceoperator-7555bb584c-dkczr   1/1     Terminating   0          6m22s
example-ibmserviceoperator-7555bb584c-zfctd   1/1     Terminating   0          6m22s
simple-operator-694c78f684-294kz              1/1     Terminating   0          13m
```

this is a microk8s cluster as well. I believe the issue here is that the `hzn unregister` command should fully delete the pods because I'm seeing an issue of the terminating operator retaining a "lock" on the ""Leader" role which does not let me subsequently running operators start their jobs, as you can see below

```
root@gormand1:~# kubectl logs simple-operator-694c78f684-294kz -n openhorizon-agent
{"level":"info","ts":1590081555.2479174,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1590081555.248013,"logger":"cmd","msg":"Go Version: go1.14.3"}
{"level":"info","ts":1590081555.2480578,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1590081555.2480826,"logger":"cmd","msg":"Version of operator-sdk: v0.17.1"}
{"level":"info","ts":1590081555.2484837,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1590081555.5459065,"logger":"leader","msg":"Found existing lock","LockOwner":"simple-operator-67876bdc95-2zw27"}
{"level":"info","ts":1590081555.55766,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590081556.6904442,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590081559.0776932,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590081563.6256022,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590081572.3416765,"logger":"leader","msg":"Not the leader. Waiting."}

...manually delete the pods with the kubectl command...

{"level":"info","ts":1590081987.0183904,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590082005.7970533,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1590082006.0565271,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1590082006.0658631,"logger":"cmd","msg":"Registering Components."}
```

**Comment by t-fine** [comment] 2020-05-21 18:22
Comment from Varatep
--------------------------------------------

I'm able to reproduce this on @t-fine's cluster as well.

## Background info

The cluster seems to be stuck in a terminating state with no indicators in the logs.
We might be able to assume that this was a result of switching policies since his cluster matched with my policy and started an agreement and the corresponding pods. Then we created another policy that matched with the node, and very shortly after, deleted the original policy the node was matching on. It’s currently listing both agreements and the pods are stuck in a terminating state.

## Agreements

```bash
[agentuser@agent-797f9595d6-mbmsr ~]$ hzn agreement list
[
  {
    "name": "Policy for mycluster/tfine-cluster-apollo1 merged with mycluster/varatep-service_1.0.0_amd64-policy",
    "current_agreement_id": "dfc0b5c4655158cd54f6bb599b3f36105de884803a7d1529e4dec801fde1596e",
    "consumer_id": "IBM/mycluster-agbot",
    "agreement_creation_time": "2020-05-15 22:44:32 +0000 UTC",
    "agreement_accepted_time": "2020-05-15 22:44:42 +0000 UTC",
    "agreement_finalized_time": "2020-05-15 22:44:43 +0000 UTC",
    "agreement_execution_start_time": "2020-05-15 22:44:48 +0000 UTC",
    "agreement_data_received_time": "",
    "agreement_protocol": "Basic",
    "workload_to_run": {
      "url": "varatep-service",
      "org": "mycluster",
      "version": "1.0.0",
      "arch": "amd64"
    }
  },
  {
    "name": "Policy for mycluster/tfine-cluster-apollo1 merged with mycluster/troy.operator_0.0.1_amd64",
    "current_agreement_id": "60a975cacbd808d30d47385113d51c30f6bd8e10ec4761b6093268b7d3826776",
    "consumer_id": "IBM/mycluster-agbot",
    "agreement_creation_time": "2020-05-15 22:44:56 +0000 UTC",
    "agreement_accepted_time": "2020-05-15 22:45:05 +0000 UTC",
    "agreement_finalized_time": "2020-05-15 22:45:22 +0000 UTC",
    "agreement_execution_start_time": "2020-05-15 22:45:11 +0000 UTC",
    "agreement_data_received_time": "",
    "agreement_protocol": "Basic",
    "workload_to_run": {
      "url": "troy.operator",
      "org": "mycluster",
      "version": "0.0.1",
      "arch": "amd64"
    }
  }
]
```

## Pods

```bash
root@gormand1:~# kubectl get pods -n openhorizon-agent
NAME                                   READY   STATUS        RESTARTS   AGE
agent-797f9595d6-mbmsr                 1/1     Running       0          5d2h
topservice-765f58848-xtb5f             1/1     Terminating   0          5d1h
topservice-operator-7b6858f656-jm8pb   1/1     Terminating   0          5d1h
topservice-operator-944f55857-5k7t8    1/1     Running       1          2d21h
```

## Logs

```bash
  "2020-05-15 22:44:56:   Node received Proposal message using agreement 60a975cacbd808d30d47385113d51c30f6bd8e10ec4761b6093268b7d3826776 for service mycluster/troy.operator from the agbot IBM/mycluster-agbot.",
  "2020-05-15 22:45:06:   Agreement reached for service troy.operator. The agreement id is 60a975cacbd808d30d47385113d51c30f6bd8e10ec4761b6093268b7d3826776.",
  "2020-05-15 22:45:06:   Start dependent services for mycluster/troy.operator.",
  "2020-05-15 22:45:06:   Start workload service for mycluster/troy.operator.",
  "2020-05-15 22:45:11:   Workload service containers for mycluster/troy.operator are up and running.",
```

**Comment by linggao** [comment] 2020-05-22 18:52
Cannot reproduce. Works on my microk8s cluster. 
````
# microk8s.kubectl get pod  -n openhorizon-agent
NAME                                   READY   STATUS        RESTARTS   AGE
agent-69d56c544c-dx6hq                 1/1     Running       4          46h
topservice-644cc6d8d9-4277s            0/1     Terminating   8          16m
topservice-operator-5866976754-j8whg   0/1     Terminating   0          16m
````
````
# microk8s.kubectl get pod  -n openhorizon-agent
NAME                     READY   STATUS    RESTARTS   AGE
agent-69d56c544c-dx6hq   1/1     Running   4          46h
````

**Comment by linggao** [comment] 2020-05-22 19:42
I am running with horizon 2.26.8.  t-fine was running with 2.26.7.  I tried with his operator. 
# microk8s.kubectl get pod  -n openhorizon-agent
NAME                                          READY   STATUS        RESTARTS   AGE
agent-69d56c544c-dx6hq                        1/1     Running       4          46h
example-ibmserviceoperator-57d84fd648-dd7h8   1/1     Terminating   0          2m35s
example-ibmserviceoperator-57d84fd648-x6p69   1/1     Terminating   0          2m35s
example-ibmserviceoperator-57d84fd648-zd8sd   1/1     Terminating   0          2m35s
simple-operator-7f5cb6f466-cx9mm              0/1     Terminating   0          2m40s
````
````
# microk8s.kubectl get pod  -n openhorizon-agent
NAME                     READY   STATUS    RESTARTS   AGE
agent-69d56c544c-dx6hq   1/1     Running   4          46h
````

**Comment by linggao** [comment] 2020-05-23 19:05
With PR 1796,  there are 2 problems fixed.
1. Fixed the deepclean part for cluster node
2. Fixed a problem when unregistration hung.

**Comment by JShelf** [comment] 2020-05-27 19:48
I was able to replicate this bug on 2.26.8 with the same service however, under a single policy. 

`hzn agreement list`

`[
  {
    "name": "Policy for mycluster/mcgj-test-cluster-3 merged with mycluster/peekTest-serviceChange",
    "current_agreement_id": "827bb0d123fa23fa0a48c68a0178b189fd99b84d37e7a95b830a2694b383a443",
    "consumer_id": "IBM/mycluster-agbot",
    "agreement_creation_time": "2020-05-27 12:59:18 +0000 UTC",
    "agreement_accepted_time": "2020-05-27 12:59:34 +0000 UTC",
    "agreement_finalized_time": "2020-05-27 12:59:51 +0000 UTC",
    "agreement_execution_start_time": "2020-05-27 12:59:40 +0000 UTC",
    "agreement_data_received_time": "",
    "agreement_protocol": "Basic",
    "workload_to_run": {
      "url": "ibm.operator",
      "org": "mycluster",
      "version": "1.0.0",
      "arch": "amd64"
    }
  }
]`


`kubectl logs simple-operator-57958556cc-q998m -n openhorizon-agent`
`{"level":"info","ts":1590584381.3269043,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1590584381.327027,"logger":"cmd","msg":"Go Version: go1.14.3"}
{"level":"info","ts":1590584381.3270638,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1590584381.3270814,"logger":"cmd","msg":"Version of operator-sdk: v0.17.1"}
{"level":"info","ts":1590584381.327613,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1590584381.6245387,"logger":"leader","msg":"Found existing lock","LockOwner":"simple-operator-7d5d6c5ffc-kj8mt"}
{"level":"info","ts":1590584381.639061,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584382.7905471,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584385.1813047,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584389.7406561,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584398.5454514,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584415.9270144,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584434.144618,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584450.3793826,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584466.9289446,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584483.2584999,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584500.2425718,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584517.9089527,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584536.7524457,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584553.4578066,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584570.694502,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584587.7400606,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584605.252003,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584622.1826243,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584639.1434467,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584657.3413208,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584674.0623176,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584690.7285514,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584707.9016805,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584725.750197,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584744.5248682,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584761.480564,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584778.4449048,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584796.8729393,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1590584813.5522974,"logger":"leader","msg":"Not the leader. Waiting."}`

**Comment by linggao** [comment] 2020-05-30 00:03
I ran the same service on Jon's node and it worked fine. 
I went on Troy's node, it always happens. And the pods could be not deleted even by kubectl command without --force option.

**Comment by linggao** [comment] 2020-06-02 14:13
This problem happens on a few agent clusters with microk8s. When this happens the anax thinks the services are shutdown already. So the new agreement can be formed. However, if the new agreements are using the same operator, the new app pods cannot be brought up. To solve this problem, user has to delete the old operator pod using the following command:
````
microk8s.kubectl delete pod ${POD} -n openhorizon-agent  --force --grace-period 0
````
After the this the new application pod will start working.

**Comment by bmpotter** [comment] 2020-06-08 13:58
My testing has confirmed that this problem only seems to occur with microk8s on fyre VMs. (I don't see it with k3s or OCP on fyre VMs.) I added a note about this in the KC documentation, including the cmds to clean up. Also, `agent-uninstall.sh` has been enhanced to clean up from this case.

So i think we can close this issue.

**Closed** 2020-06-08 14:00 UTC
Labels: bug, p3
