### ISSUE TITLE
Pattern removal from exchange help text inconsistency

### ISSUE THREAD

**Issue by edgedock** [open-horizon/anax#909] opened 2019-04-30 04:44 UTC
When I tried to remove a pattern without any option it failed to remove giving 403. When I used -f option it successfully removed the pattern with code 204. 
"-f" option is described as "not to show the confirmation promp"t, but in this case it forced the  deletion of the pattern as well. Is this behavior expected?
  
root@edgedev01:mqtt_kafka# hzn exchange pattern remove sanjeev@ibm.com/cpu2msghub
Are you sure you want to remove pattern 'sanjeev@ibm.com/cpu2msghub' from the Horizon Exchange? [y/N]: y
Error: bad HTTP code 403 from DELETE https://alpha.edge-fabric.com/v1/orgs/sanjeev@ibm.com/patterns/cpu2msghub

root@edgedev01:mqtt_kafka# hzn exchange pattern remove -v -f sanjeev@ibm.com/cpu2msghub
[verbose] The exchange url: https://alpha.edge-fabric.com/v1
[verbose] DELETE https://alpha.edge-fabric.com/v1/orgs/sanjeev@ibm.com/patterns/cpu2msghub
[verbose] HTTP code: 204

**Comment by bmpotter** [comment] 2019-04-30 14:25
Sanjeev, no this is not expected behavior. The prompt is done at the `hzn` level, not the exchange, so i assigned it to ling to take a look.

**Comment by bmpotter** [comment] 2019-05-06 14:43
Sanjeev,

I'm not able to recreate this in either prod or staging. It works for me in both environments. Please test again and try to narrow down what the problem is. Thx

**Comment by MaxMcAdam** [comment] 2019-06-25 19:42
Could not replicate in 2.23.10

**Closed by MaxMcAdam** 2019-06-25 19:42 UTC
Labels: bug, need info, p3
