### ISSUE TITLE
Problems installing on k3s cluster

### ISSUE THREAD

**Issue by TheMosquito** [open-horizon/anax#1898] opened 2020-07-06 17:57 UTC
On ubuntu 18.04, x86/64, 96 cores, 200GB RAM, using the IEAM 4.1 release versions, on a k3s cluster, trying to install an IEAM agent for this cluster:

**Issue 2:**
In:https://www.ibm.com/support/knowledgecenter/SSFKVV_4.1/devices/installing/edge_cluster_agent.html#install_lite
(in the k3s section):
3. Extract the agent-install.sh script from the tar file:
 tar -zxvf agentInstallFiles-x86_64-Cluster.tar.gz agent-install.sh
This extracts only the agent-install.sh script, but the later command expect all the files to have been extracted. So that later command failed. When we went back and extracted all the files from this tarball the later command worked. So I think you should remove the last argument from the above command so it will extract all files.

**Clarification by Bruce:** The `agent-install.sh` command that is run later on uses the `-z agentInstallFiles-x86_64-Cluster.tar.gz` flag, so `agent-install.sh` should have access to all of the files w/o the user extracting them manually as glen suggested above. Need to debug with glen why that didn't work.

**Issue 4:**
(in the same file, same section)
The instructions do not tell the user to set HZN_ORG_ID at all, but this is required by the  agent-install.sh script.

**Clarification by Bruce:** `HZN_ORG_ID` is set in `agent-install.cfg`, so shouldn't have to be set in the environment as glen suggested above. Need to debug with glen why that didn't work.

**Comment by jiportilla** [comment] 2020-07-06 19:14
related issue - https://github.ibm.com/Edge-Fabric/docs/issues/530

**Comment by LiilyZhang** [comment] 2020-07-07 13:14
Tested issue 4 in my SL VM and "ben" machine that @TheMosquito is working on, can't reproduce in both places

**Comment by LiilyZhang** [comment] 2020-07-07 15:55
Tested issue 2 for k3s on "ben" machine:

```
./agent-install.sh -D cluster -z ieam41-w3-agentInstallFiles-x86_64-Cluster.tar.gz -d bizdev-ben-96core -l 5
```
It failed because `HZN_ORG_ID` is not set in `agent-install.cfg` or env

`agent-install.cfg` from `ieam41-w3-agentInstallFiles-x86_64-Cluster.tar.gz` (mask some chars in url):
```
HZN_EXCHANGE_URL=https://icp-console.ieam41-w3-******-south.containers.appdomain.cloud/edge-exchange/v1/
HZN_FSS_CSSURL=https://icp-console.ieam41-w3-*******-south.containers.appdomain.cloud/edge-css/
HZN_ORG_ID=
HZN_MGMT_HUB_CERT_PATH=agent-install.crt
AGENT_NAMESPACE=openhorizon-agent
AGENT_IMAGE_TAG=4.1.0
```

After set HZN_ORG_ID in env, agent-install.sh with `-z` runs successfully.

**Comment by LiilyZhang** [comment] 2020-07-07 16:44
Comfirmed with @edgedock , `-o` is not specified when executing `edgeNodeFiles.sh`. So edgeNodeFiles.sh works as expected as well. 

Closed as both @edgedock and @TheMosquito agreed

**Closed** 2020-07-07 16:45 UTC
